In [1]:
import numpy as np
import cv2
import random

In [2]:
img = cv2.imread('C:/Documents-Summer2018/CVIP/PA2/Butterfly.jpg')
row,col,colorsp = img.shape
segmented_img = np.zeros((img.shape))
print(segmented_img.shape)
ref_table = np.zeros((row * col + 1,5))
x,y = ref_table.shape
print(ref_table.shape)
h = 90
iters = 40

(333, 500, 3)
(166501, 5)


In [3]:
#rearranging into feature matrix
t = 0
for i in range(0,row):
    for j in range(0,col):
        ref_table[t][0]=img[i][j][0]
        ref_table[t][1]=img[i][j][1]
        ref_table[t][2]=img[i][j][2]
        ref_table[t][3]=i
        ref_table[t][4]=j
        t+=1        
        
    

In [4]:
print (x,len(ref_table))
print(img)
print(ref_table)


166501 166501
[[[21 68 36]
  [21 70 38]
  [23 71 42]
  ...
  [21 47 23]
  [24 48 24]
  [27 47 24]]

 [[20 64 33]
  [20 67 35]
  [18 66 37]
  ...
  [19 49 24]
  [23 49 25]
  [26 50 26]]

 [[20 62 31]
  [18 62 31]
  [14 60 31]
  ...
  [15 52 26]
  [21 53 28]
  [24 54 29]]

 ...

 [[12 72 42]
  [18 78 48]
  [22 82 52]
  ...
  [21 58 32]
  [25 63 35]
  [26 65 33]]

 [[ 7 67 37]
  [11 71 41]
  [16 76 46]
  ...
  [20 53 32]
  [23 58 32]
  [24 59 32]]

 [[ 7 67 37]
  [11 71 41]
  [16 76 46]
  ...
  [10 43 22]
  [13 48 22]
  [14 49 22]]]
[[ 21.  68.  36.   0.   0.]
 [ 21.  70.  38.   0.   1.]
 [ 23.  71.  42.   0.   2.]
 ...
 [ 13.  48.  22. 332. 498.]
 [ 14.  49.  22. 332. 499.]
 [  0.   0.   0.   0.   0.]]


In [5]:
print('Initial length of Reference table :',len(ref_table))
iteration_no = 1

while(len(ref_table)>0):
    print('Current length of Reference table :',len(ref_table))
    print('Iter : ',iteration_no)
    iteration_no+=1    
    fetched = random.randint(0,len(ref_table)-1)#https://www.pythoncentral.io/how-to-generate-a-random-number-in-python/
        
    dist = 0;
    Cluster_ls = []

    for i in range(0,len(ref_table)):
        dist = np.linalg.norm(ref_table[fetched]-ref_table[i])#https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy
        if dist < h:
            Cluster_ls.append(i)
    print('Cluster Size:',len(Cluster_ls))
    if(len(Cluster_ls) > 0):
        m1,m2,m3,m4,m5 = 0,0,0,0,0
        for i in range(0,len(Cluster_ls)):
            idx = Cluster_ls[i]
            m1 += ref_table[idx][0]
            m2 += ref_table[idx][1]
            m3 += ref_table[idx][2]
            m4 += ref_table[idx][3]
            m5 += ref_table[idx][4]

        
        
        newMean = np.zeros((1,5))
        l1 = len(Cluster_ls)    
        newMean[0][0] = m1/l1
        newMean[0][1] = m2/l1
        newMean[0][2] = m3/l1
        newMean[0][3] = m4/l1
        newMean[0][4] = m5/l1

                  
        new_dist = np.linalg.norm(ref_table[fetched]-newMean[0])#https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy
  
#         print('New Distance :',new_dist)


        if(new_dist <= iters):
            for i in range(0,len(Cluster_ls)):
                index = Cluster_ls[i]
                x = int(ref_table[index][3])
                y = int(ref_table[index][4])
                segmented_img[x][y][0] = newMean[0][0]
                segmented_img[x][y][1] = newMean[0][1]
                segmented_img[x][y][2] = newMean[0][2]

            ref_table = np.delete(ref_table,Cluster_ls,0)

        else:
            x = int(ref_table[fetched][3])                
            y = int(ref_table[fetched][4])
            segmented_img[x][y][0] = ref_table[fetched][0]
            segmented_img[x][y][1] = ref_table[fetched][1]
            segmented_img[x][y][2] = ref_table[fetched][2]
            ref_table = np.delete(ref_table,fetched,0)           



print(segmented_img)
      
cv2.imshow("Segmented Image:",segmented_img/255)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.imwrite('C:/Documents-Summer2018/CVIP/PA2/MS/SegmentedImg_90_40.png',segmented_img)
        

Initial length of Reference table : 166501
Current length of Reference table : 166501
Iter :  1
Cluster Size: 12365
Current length of Reference table : 154136
Iter :  2
Cluster Size: 12994
Current length of Reference table : 141142
Iter :  3
Cluster Size: 5899
Current length of Reference table : 135243
Iter :  4
Cluster Size: 15200
Current length of Reference table : 120043
Iter :  5
Cluster Size: 11994
Current length of Reference table : 108049
Iter :  6
Cluster Size: 5475
Current length of Reference table : 108048
Iter :  7
Cluster Size: 10187
Current length of Reference table : 97861
Iter :  8
Cluster Size: 9392
Current length of Reference table : 88469
Iter :  9
Cluster Size: 3827
Current length of Reference table : 84642
Iter :  10
Cluster Size: 3648
Current length of Reference table : 80994
Iter :  11
Cluster Size: 6346
Current length of Reference table : 74648
Iter :  12
Cluster Size: 4587
Current length of Reference table : 70061
Iter :  13
Cluster Size: 7585
Current length of 

True